### ISSUE TITLE
Separate field for schema version

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-schema#1]
If we adjust the schemas and have different versions, it should somehow be clear to which schema version a descriptor belongs. If only minor changes were made, it's fine to use older schema versions.
If no schema version is specified, just use the latest schema.

Also the descriptor generator should generate and validate based on schemas of a specific version.

**Comment by mpeuster** [comment]
Package descriptors have `descriptor_version: "0.9"` ... we should put this keyword in all descriptors.

**Comment by stefanbschneider** [comment]
Just included and set `descriptor_version` in all schemas and descriptors
