### ISSUE TITLE
bandwidth_units missing in nsd-schema.yml

### ISSUE THREAD

**Issue by antonroman** [sonata-nfv/tng-schema#128]
bandwidth_units definition is missing in nsd-schema.yml and the validation is failing when bandwidth QoS contraints are added in the NS descriptor. In vnfd-schema is properly defined:
bandwidth_units:
enum:
- "bps" # Bit per second
- "kbps" # Kilobit per second
- "Mbps" # Megabit per second
- "Gbps" # Gigabit per second
- "Tbps" # Terabit per second

I will create a PR to add this missing definition.

**Comment by stefanbschneider** [comment]
Is this solved by now? If so, we should close the issue for v5.0

**Comment by stefanbschneider** [comment]
I'll close for now. Feel free to reopen, if the issue still exists.
