### ISSUE TITLE
Add descriptor_type to the descriptors

### ISSUE THREAD

**Issue by stefanbschneider** [sonata-nfv/tng-schema#2]
Problem:
Someone gives you two YAML files, a NSD and a VNFD. But you are not told which of the files is the NSD and which the VNFD. To find out, you can either check the fields in the descriptor and make a qualified guess or we could directly include a type field in the descriptor's header that tells us.

This would look like this:
```yams
descriptor_version: "1.0"
descriptor_type: "eu.5gtango.nsd"
...
```

Possible values for the type could be (but are not limited to):
- `eu.5gtango.nsd`
- `eu.5gtango.vnfd`
- `eu.5gtango.msd`
- `eu.sonata-nfv.nsd`
- `eu.sonata-nfv.vnfd`
- `eu.sonata-nfv.msd`

This will also support to distinguish VNF only vs. NS packages.

**Comment by stefanbschneider** [comment]
I suggest to only allow values based on the layer tags defined here: https://github.com/sonata-nfv/tng-schema/wiki/PkgSpec_LATEST#list-of-pre-defined-tags
Thus using `eu.sonata` instead of  `eu.sonata-nfv` (or adjusting the predefined tags in the wiki specification)

**Comment by stefanbschneider** [comment]
I just included descriptor types in all schemas and descriptor examples.
I documented the descriptor types here: https://github.com/sonata-nfv/tng-schema/wiki/Descriptor-Type

**Comment by mpeuster** [comment]
I would suggest to change the `decriptor_type` to use the MIME types for the 5GTANGO descriptors as defined here: https://github.com/sonata-nfv/tng-schema/wiki/PkgSpec_LATEST#5gtango-specific-mime-types

Using layer tags for it seems to be a bit strange. We cannot express schemas for e.g. OSM. What do you think?

(I am also re-opening this issue because I need to add the `descriptor_type` field to the NAPD and REF schemas, examples and specs)

**Comment by stefanbschneider** [comment]
As we decided to replace `descriptor_version` and `descriptor_type` with `descriptor_schema` (path to the corresponding schema), I will remove the `descriptor_type` wiki page.

**Comment by stefanbschneider** [comment]
We still have to implement/adjust the validator to check descriptors against the referenced schema in `descriptor_schema`.

**Comment by stefanbschneider** [comment]
I don't think, we need this anymore
