### ISSUE TITLE
Add QoS support to connection points and add additional IA fields

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-schema#89]
See:
* https://github.com/sonata-nfv/tng-sp-ia/wiki/QoS
* https://github.com/sonata-nfv/tng-sp-ia/wiki/Miscellaneous

**Comment by stefanbschneider** [comment]
Example VNFD here: https://github.com/sonata-nfv/tng-schema/blob/master/function-descriptor/examples/qos-vnfd.yml#L71

Same features are supported for connection points and vLinks in NSDs.
